### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by cmpute** [kuba160/ddb_gui_qt5#1]
Thanks for your work! I'm really happy to use Qt if it's available, since I'm using KDE. I tried to compile the library, and I got this error 
```
../MainWindow.cpp:2:10: fatal error: ui_MainWindow.h: No such file or directory
 #include "ui_MainWindow.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:1039: recipe for target 'MainWindow.o' failed
make: *** [MainWindow.o] Error 1
make: *** Waiting for unfinished jobs....
```

I'm not familiar with Qt, so could you please give any suggestions on this?

**Comment by kuba160** [comment]
ui_X files are ones generated from X.ui. I recently moved everything from MainWindow.ui to DefaultActions.ui, looks like I forgot to delete all references to it. Still not sure if it was a good idea tho...
