### ISSUE TITLE
[Qt 6] Two windows

### ISSUE THREAD

**Issue by begin-theadventure** [kuba160/ddb_gui_qt5#6]
Two windows are opened, one with the old look and the other with the new.

**Comment by kuba160** [comment]
I try to support both Qt Widgets and Qt Quick interface, having 2 windows is done for testing purposes. There should be an option that allows to choose the interface.

**Comment by begin-theadventure** [comment]
> There should be an option that allows to choose the interface.

I agree, that would be the best solution!
